### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by noob-master147** [noob-master147/Personal-Website#1]
Thumbnails for GitHub, Facebook and LinkedIn are not correct

**Comment by maddyBoy** [comment]
@noob-master147 is this issue is related to https://github.com/noob-master147/Personal-Website/pull/2

**Comment by AdrianJVillalobos** [comment]
Hello, I'm interested in this issue, is still active? I would like to take this at @NovaHelm can you give me more details?

**Comment by noob-master147** [comment]
hey @AdrianJVillalobos 
this is still open 
you can edit the thumbnails and even refine the themes and all
