### ISSUE TITLE
Adding endpoints and more pages to the website 

### ISSUE THREAD

**Issue by noob-master147** [noob-master147/Personal-Website#13]
### Add a Project, Blog, Resume page to the Portfolio website and connect it to the navbar.
feel free to create new HTML and CSS files under a directory named `Endpoints`

Open a PR against the branch `Endpoints`

**Comment by RayceeM** [comment]
Hey can I work on this issue?

**Comment by noob-master147** [comment]
## Go ahead @RayceeM  
Feel free to use your creative mind and do your Best, just abide to the guide lines
### Happy Open Sourcing

**Comment by noob-master147** [comment]
keep in mind to make the pages responsive for desktop  and mobile views

**Comment by RayceeM** [comment]
@noob-master147  I assume the github and Medium pages won't need to be added because you can add a link to redirect you to github or medium?

**Comment by noob-master147** [comment]
> @noob-master147 I assume the github and Medium pages won't need to be added because you can add a link to redirect you to github or medium?

yaa so just add a href tag which will redirect to those pages on a new window
