### ISSUE TITLE
Add responsiveness to the navbar

### ISSUE THREAD

**Issue by noob-master147** [noob-master147/Personal-Website#14]
When viewed on mobile view, the navbar is not responsive the way it should be,
Add a drop-down menu for mobile view with a hamburger icon.

add a PR against `Navbar` branch

### Happy Open Sourcing :)

**Comment by jcoyle37** [comment]
Hi, I'd like to try to fix this.

**Comment by guilhermeorcezi** [comment]
Done, please check it.
