### ISSUE TITLE
Add a Navbar to the Portfolio Website

### ISSUE THREAD

**Issue by noob-master147** [noob-master147/Personal-Website#7]
### The main routes to navbar will be as following 
1. Home
2. Projects
3. Blogs
4. Resume
5. Contact
6. Medium
7. Github

feel free to explore the navbar issue

## Things to keep in mind 
Refer to the `master` branch and make the navbar for the master code
keep the navbar right-aligned
Leave some space in the top left for personal logo

**Comment by thenewpyjiang** [comment]
Hello! I'm a participant of Hacktoberfest, can I be assigned for this issue?

**Comment by thenewpyjiang** [comment]
Oooops sorry I accidentally clicked the wrong button.

**Comment by noob-master147** [comment]
Hey !!!! 
i'm glad you want to contribute 
just keep the guidelines in mind 
### Happy Open Sourcing

**Comment by noob-master147** [comment]
@thenewpyjiang pull the new changes from the master

**Comment by thenewpyjiang** [comment]
@noob-master147 New pull request made! Please review :)

**Comment by noob-master147** [comment]
@thenewpyjiang  can you please create the PR against `Navbar` branch
